# The Machine Learning & Deep Learning Show

#### By Akanksha

In [1]:
#importing lib
import numpy as np
import pandas as pd

In [3]:
#importing data
dataset= pd.read_csv("Data/IRIS.csv")

In [5]:
dataset.head(10)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [6]:
dataset["species"] = dataset["species"].astype('category')
dataset["Encoded_Species"] = dataset["species"].cat.codes

In [10]:
dataset

sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
5             5.4          3.9           1.7          0.4     Iris-setosa   
6             4.6          3.4           1.4          0.3     Iris-setosa   
7             5.0          3.4           1.5          0.2     Iris-setosa   
8             4.4          2.9           1.4          0.2     Iris-setosa   
9             4.9          3.1           1.5          0.1     Iris-setosa   
10            5.4          3.7           1.5          0.2     Iris-setosa   
11            4.8          3.4           1.6          0.2     Iris-setosa   
12            4.8          3.0           1.4          0.1     Iris-setosa   
13            4.3          3.0           1.1          0.1     Iris-setosa   
14            5.8          4.0           1.2          0.2     Iris-setosa   
15            5.7          4.4           1.5          0.4     Iris-setosa   
16            5.4          3.9           1.3          0.4     Iris-setosa   
17            5.1          3.5           1.4          0.3     Iris-setosa   
18            5.7          3.8           1.7          0.3     Iris-setosa   
19            5.1          3.8           1.5          0.3     Iris-setosa   
20            5.4          3.4           1.7          0.2     Iris-setosa   
21            5.1          3.7           1.5          0.4     Iris-setosa   
22            4.6          3.6           1.0          0.2     Iris-setosa   
23            5.1          3.3           1.7          0.5     Iris-setosa   
24            4.8          3.4           1.9          0.2     Iris-setosa   
25            5.0          3.0           1.6          0.2     Iris-setosa   
26            5.0          3.4           1.6          0.4     Iris-setosa   
27            5.2          3.5           1.5          0.2     Iris-setosa   
28            5.2          3.4           1.4          0.2     Iris-setosa   
29            4.7          3.2           1.6          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
120           6.9          3.2           5.7          2.3  Iris-virginica   
121           5.6          2.8           4.9          2.0  Iris-virginica   
122           7.7          2.8           6.7          2.0  Iris-virginica   
123           6.3          2.7           4.9          1.8  Iris-virginica   
124           6.7          3.3           5.7          2.1  Iris-virginica   
125           7.2          3.2           6.0          1.8  Iris-virginica   
126           6.2          2.8           4.8          1.8  Iris-virginica   
127           6.1          3.0           4.9          1.8  Iris-virginica   
128           6.4          2.8           5.6          2.1  Iris-virginica   
129           7.2          3.0           5.8          1.6  Iris-virginica   
130           7.4          2.8           6.1          1.9  Iris-virginica   
131           7.9          3.8           6.4          2.0  Iris-virginica   
132           6.4          2.8           5.6          2.2  Iris-virginica   
133           6.3          2.8           5.1          1.5  Iris-virginica   
134           6.1          2.6           5.6          1.4  Iris-virginica   
135           7.7          3.0           6.1          2.3  Iris-virginica   
136           6.3          3.4           5.6          2.4  Iris-virginica   
137           6.4          3.1           5.5          1.8  Iris-virginica   
138           6.0          3.0           4.8          1.8  Iris-virginica   
139           6.9          3.1           5.4          2.1  Iris-virginica   
1

In [11]:
#define X & Y
X= dataset.iloc[:,0:4].values

In [12]:
Y= dataset.iloc[:,-1].values

In [13]:
#split 
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test= train_test_split(X,Y, test_size=0.1)

## Logistics Regression

In [14]:
from sklearn.linear_model import LogisticRegression
logclass= LogisticRegression()
logclass.fit(X_train, Y_train)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
pred_log=logclass.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, pred_log)

array([[1, 0, 0],
       [0, 7, 0],
       [0, 1, 6]])

Accuracy can be found as 1+7+6 / 1+7+6+1. However, it can also be found by the code below.

In [17]:
acc_log = logclass.score(X_test, Y_test)
acc_log

0.9333333333333333

## KNN Classifier

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn.fit(X_train, Y_train)
Y_pred= knn.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[1, 0, 0],
       [0, 7, 0],
       [0, 0, 7]])

In [20]:
acc_KNN = knn.score(X_test,Y_test)
acc_KNN

1.0

## Decision Tree

In [21]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(X_train,Y_train)
pred_DT=DT.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, pred_DT)

array([[1, 0, 0],
       [0, 7, 0],
       [0, 1, 6]])

In [23]:
acc_DT = DT.score(X_test,Y_test)
acc_DT

0.9333333333333333

## Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier
Rf=RandomForestClassifier()
Rf.fit(X_train,Y_train)
pred_rf=Rf.predict(X_test)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, pred_rf)

array([[1, 0, 0],
       [0, 7, 0],
       [0, 1, 6]])

In [27]:
acc_rf = Rf.score(X_test, Y_test)
acc_rf

0.9333333333333333

## Which model performs best accuracy wise?

KNN classifier performs the best accuracy wise as it shows the result=1 and others show the similar results accuracy wise.